name: chat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^9.0.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3
  build_runner: ^2.4.7
  get_it: ^8.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

